nav_links:
  type: objects
  default:
    - group_name: staff
      group_exclude: ''
      content: add your content here
      button_url: /
      button_text: home
      button_icon: house
  schema:
    name: nav link
    identifier: text
    properties:
      group_name:
        type: string
        required: true
        validations:
          min_length: 1
          max_length: 1000
      group_exclude:
        type: string
        validations:
          max_length: 1000
      content:
        type: string
        required: true
        validations:
          min_length: 1
          max_length: 1000
      button_url:
        type: string
        validations:
          max_length: 2048
          url: true
      button_text:
        type: string
        validations:
          max_length: 1000
      button_icon:
        type: string
        validations:
          max_length: 200
